#!/bin/bash

#Password Generator Script

echo "Password Generator Script"
read -p "Enter the password lenght: " PASS_LENGTH
for VAR in $(seq 1 );
do
    openssl rand -base64 48 | cut -c1-$PASS_LENGTH
done
