#!/bin/bash
LENGTH=$1
SC=$2
passgen() {
        for VAR in $(seq 1 );
do
    openssl rand -base64 48 | cut -c1-$LENGTH
done
}

passgenparam() {
        pwgen -s -N 1 -cny $LENGTH
}

if [ $SC = 'y' ]; then
passgenparam
elif [ $SC = 'n' ]; then
passgen
fi
