#!/bin/bash

read -p "Number of password symbols" LENGTH
read -p "Use special characters y/n?" SC

passgen() {
        for VAR in $(seq 1 );
do
    openssl rand -base64 48 | cut -c1-$LENGTH
done
}

passgenparam() {
        pwgen -s -N 1 -cny $LENGTH
}

if [ $SC = 'y' ]; then
passgenparam
elif [ $SC = 'n' ]; then
passgen
fi
